services:
  mongo:
    image: "mongo"
    ports:
      - "8080:27017"
  backend:
    build: "./backend"
    ports:
      - "8000:5000"
    depends_on:
      - mongo
    env_file:
      - "./backend/.env.prod"
  frontend:
    build: "./frontend"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - "./frontend/.env.prod"
